# Generated by Selenium IDE
#参考：https://note.com/kohaku935/n/n87903c010d28
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver import ChromeOptions
import os

downloadsFilePath = '/Volumes/GoogleDrive/共有ドライブ/社内用（社外共有禁止）/06_システム運用/02.体験会予約管理システム/22年春集客シート連携/csv'

# Selenium初期化
def initialize():
   options = webdriver.ChromeOptions()
   prefs = {
       "download.default_directory": downloadsFilePath,
   }
   options.add_experimental_option("prefs", prefs)
   driver_file = r'/usr/local/bin/chromedriver' # ドライバのPathを設定
   return webdriver.Chrome(driver_file,options=options)

# 指定したフォルダの最新のファイルパスを取得する
def get_latest_file_path(path):
   file_path = ''
   if len(os.listdir(path)) != 0:
       file_path = max (
           [ os.path.join(path, f) for f in os.listdir(path)], 
           key = os.path.getctime
       )
   
   return file_path

driver = webdriver.Chrome('/usr/local/bin/chromedriver')

URL ='https://manage-youmemiru.resv.jp/manage/login.php'

driver = initialize()

driver.get(URL)



print(driver.title)
driver.set_window_size(1420, 1068)
driver.find_element(By.NAME, "loginid").click()
element = driver.find_element_by_name('loginid')
element.send_keys('manager')

driver.find_element(By.NAME, "loginpw").click()
element = driver.find_element_by_name('loginpw')
element.send_keys('mg@12345')
element.submit()


driver.find_element_by_link_text("予約データ").click()
time.sleep(2)
driver.find_element_by_link_text("予約一覧").click()

driver.find_element(By.ID, "search_conditions_onoff").click()

driver.find_element(By.ID, "i_symd").click()
driver.find_element(By.ID, "i_symd").send_keys("today")
driver.find_element(By.NAME, "submit1").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".btn-block:nth-child(1)").click()
time.sleep(5)

# ダウンロードしたフォルダから最新のファイルを取得
path = os.path.join(os.getcwd(), downloadsFilePath )
file_path = get_latest_file_path(path)
print(file_path)


driver.close()